### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by worldveil** [ray-project/lightgbm_ray#2]
Setup
```bash
conda create --name lgbm python=3.8
conda activate lgbm
conda install lightgbm
pip install lightgbm_ray
```

Script: 

```python
# light_ray.py
from lightgbm_ray import RayDMatrix, RayParams, train
from sklearn.datasets import load_breast_cancer

train_x, train_y = load_breast_cancer(return_X_y=True)
train_set = RayDMatrix(train_x, train_y)

evals_result = {}
bst = train(
    {
        "objective": "binary",
        "metric": ["binary_logloss", "binary_error"],
    },
    train_set,
    num_boost_round=10,
    evals_result=evals_result,
    valid_sets=[train_set],
    valid_names=["train"],
    verbose_eval=False,
    ray_params=RayParams(num_actors=2, cpus_per_actor=2))


bst.booster_.save_model("model.lgbm")
```

Exception:
```
% python light_ray.py 
Traceback (most recent call last):
  File "light_ray.py", line 1, in <module>
    from lightgbm_ray import RayDMatrix, RayParams, train
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/lightgbm_ray/__init__.py", line 1, in <module>
    from lightgbm_ray.main import RayParams, train, predict
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/lightgbm_ray/main.py", line 44, in <module>
    from lightgbm import LGBMModel, LGBMRanker, Booster
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/lightgbm/__init__.py", line 8, in <module>
    from .basic import Booster, Dataset, register_logger
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/lightgbm/basic.py", line 95, in <module>
    _LIB = _load_lib()
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/lightgbm/basic.py", line 86, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/ctypes/__init__.py", line 459, in LoadLibrary
    return self._dlltype(name)
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
```

**Comment by Yard1** [comment]
It looks like LightGBM wasn't installed correctly. Can you try `pip install lightgbm` instead of `conda install`?

If you are on Mac, you may need to follow Mac-specific instructions - https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#macos - it seems that first it needs to be installed using homebrew *and* then a pip/conda package can be installed.

**Comment by worldveil** [comment]
I repeated with:

```bash
brew install lightgbm
conda install jupyter -y
pip install lightgbm_ray lightgbm
```

but now got:

```
% python light_ray.py 
/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py:57: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  warnings.warn(
2021-07-14 15:15:28,252 INFO services.py:1272 -- View the Ray dashboard at http://127.0.0.1:8266
Traceback (most recent call last):
  File "light_ray.py", line 8, in <module>
    bst = train(
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/lightgbm_ray/main.py", line 917, in train
    ray.init()
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/ray/worker.py", line 802, in init
    _global_node = ray.node.Node(
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/ray/node.py", line 243, in __init__
    address_info = (ray._private.services.get_address_info_from_redis(
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/ray/_private/services.py", line 309, in get_address_info_from_redis
    return get_address_info_from_redis_helper(
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/ray/_private/services.py", line 266, in get_address_info_from_redis_helper
    client_table = global_state.node_table()
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/ray/state.py", line 244, in node_table
    node_info["Resources"] = self.node_resource_table(
  File "/Users/will/opt/anaconda3/envs/lgbm/lib/python3.8/site-packages/ray/state.py", line 205, in node_resource_table
    node_id = ray.NodeID(hex_to_binary(node_id))
  File "python/ray/includes/unique_ids.pxi", line 207, in ray._raylet.NodeID.__init__
  File "python/ray/includes/unique_ids.pxi", line 33, in ray._raylet.check_id
ValueError: ID string needs to have length 28, got 20
```

Deps:
```
% pip freeze | grep ray
lightgbm-ray==0.0.2
ray==1.4.1
xgboost-ray==0.1.2
```

**Comment by simon-mo** [comment]
Can't repro it with a new conda env, python3.8, and same version of lightgbm, ray...

**Comment by Yard1** [comment]
I cannot reproduce it either, both on Mac and Ubuntu.

**Comment by Yard1** [comment]
Will solved it, it was an issue on his side.
